#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative 'style_sheet'
require_relative 'rule'
require_relative 'property'
require_relative 'parser.rex'
require_relative 'literal'
require_relative 'assign'
require_relative 'variable'
require_relative 'import'
module SSS
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 95)

...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    38,    43,    44,    34,    19,    42,    40,    46,    35,    36,
    37,    39,    38,    22,    20,    34,    12,    13,    40,    16,
    35,    36,    37,    39,    38,    27,    13,    34,    14,    15,
    40,    23,    35,    36,    37,    39,    38,    27,    13,    34,
    14,   nil,    40,   nil,    35,    36,    37,    39,    38,    27,
    13,    34,    14,   nil,    40,    46,    35,    36,    37,    39,
     8,   nil,   nil,   nil,    12,    13,     8,    14,   nil,   nil,
    12,    13,     8,    14,   nil,   nil,    12,    13,   nil,    14 ]

racc_action_check = [
    48,    26,    27,    48,     8,    26,    48,    48,    48,    48,
    48,    48,    46,    14,    10,    46,    10,    10,    46,     2,
    46,    46,    46,    46,    44,    43,    43,    44,    43,     1,
    44,    15,    44,    44,    44,    44,    22,    25,    25,    22,
    25,   nil,    22,   nil,    22,    22,    22,    22,    32,    20,
    20,    32,    20,   nil,    32,    32,    32,    32,    32,    32,
     5,   nil,   nil,   nil,     5,     5,    16,     5,   nil,   nil,
    16,    16,     0,    16,   nil,   nil,     0,     0,   nil,     0 ]

racc_action_pointer = [
    69,    29,    17,   nil,   nil,    57,   nil,   nil,     0,   nil,
     9,   nil,   nil,   nil,     4,    31,    63,   nil,   nil,   nil,
    42,   nil,    32,   nil,   nil,    30,    -1,    -7,   nil,   nil,
   nil,   nil,    44,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    18,    20,   nil,     8,   nil,    -4,   nil ]

racc_action_default = [
    -2,   -40,    -1,    -3,    -6,    -7,    -9,   -10,   -40,   -12,
   -40,   -15,   -17,   -18,   -40,   -40,    -5,    -8,   -13,   -11,
   -19,   -16,   -40,    50,    -4,   -24,   -40,   -17,   -20,   -23,
   -26,   -27,   -29,   -30,   -33,   -34,   -35,   -36,   -37,   -38,
   -39,   -25,   -14,   -22,   -40,   -31,   -40,   -21,   -28,   -32 ]

racc_goto_table = [
    31,    25,    28,     3,    32,    31,    45,    18,    26,    21,
    17,    41,     2,     1,   nil,   nil,   nil,   nil,   nil,    24,
    49,   nil,    45,    31,    25,    47,    48,    18 ]

racc_goto_check = [
     6,     5,    12,     3,    15,     6,    16,     8,    10,    11,
     4,    13,     2,     1,   nil,   nil,   nil,   nil,   nil,     3,
    16,   nil,    16,     6,     5,    12,    15,     8 ]

racc_goto_pointer = [
   nil,    13,    12,     3,     5,   -19,   -20,   nil,     2,   nil,
   -12,    -1,   -18,   -14,   nil,   -18,   -26 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,     5,     6,     7,     9,    10,
   nil,    11,   nil,    29,    30,   nil,    33 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 17, :_reduce_1,
  0, 18, :_reduce_2,
  1, 18, :_reduce_3,
  3, 18, :_reduce_4,
  2, 18, :_reduce_5,
  1, 19, :_reduce_6,
  1, 19, :_reduce_none,
  2, 19, :_reduce_8,
  1, 20, :_reduce_none,
  1, 20, :_reduce_none,
  2, 23, :_reduce_11,
  1, 21, :_reduce_12,
  2, 21, :_reduce_13,
  4, 24, :_reduce_14,
  1, 25, :_reduce_15,
  2, 25, :_reduce_16,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  0, 26, :_reduce_19,
  1, 26, :_reduce_20,
  3, 26, :_reduce_21,
  2, 26, :_reduce_22,
  1, 28, :_reduce_23,
  1, 28, :_reduce_none,
  2, 28, :_reduce_25,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  3, 30, :_reduce_28,
  3, 22, :_reduce_29,
  1, 31, :_reduce_30,
  2, 31, :_reduce_31,
  3, 31, :_reduce_32,
  1, 32, :_reduce_33,
  1, 32, :_reduce_34,
  1, 32, :_reduce_35,
  1, 32, :_reduce_36,
  1, 32, :_reduce_37,
  1, 32, :_reduce_38,
  1, 32, :_reduce_39 ]

racc_reduce_n = 40

racc_shift_n = 50

racc_token_table = {
  false => 0,
  :error => 1,
  ";" => 2,
  :IMPORT => 3,
  :STRING => 4,
  "{" => 5,
  "}" => 6,
  :IDENTIFIER => 7,
  :SELECTOR => 8,
  ":" => 9,
  :VARIABLE => 10,
  "," => 11,
  :COLOR => 12,
  :NUMBER => 13,
  :DIMENSION => 14,
  :URI => 15 }

racc_nt_base = 16

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\";\"",
  "IMPORT",
  "STRING",
  "\"{\"",
  "\"}\"",
  "IDENTIFIER",
  "SELECTOR",
  "\":\"",
  "VARIABLE",
  "\",\"",
  "COLOR",
  "NUMBER",
  "DIMENSION",
  "URI",
  "$start",
  "stylesheet",
  "statements",
  "statementGroup",
  "statement",
  "rules",
  "variableDeclaration",
  "importDirective",
  "rule",
  "selector",
  "declarations",
  "selectorElement",
  "declarationGroup",
  "declaration",
  "property",
  "values",
  "value" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 14)
  def _reduce_1(val, _values, result)
     return StyleSheet.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 17)
  def _reduce_2(val, _values, result)
     return [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_3(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_4(val, _values, result)
     return val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 20)
  def _reduce_5(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_6(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.racc', 25)
  def _reduce_8(val, _values, result)
     return val[0].push(val[1]) 
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.racc', 32)
  def _reduce_11(val, _values, result)
     return Import.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 35)
  def _reduce_12(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_13(val, _values, result)
     return val[0].push(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_14(val, _values, result)
     return Rule.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 42)
  def _reduce_15(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 43)
  def _reduce_16(val, _values, result)
     return val[0] + ' ' + val[1] 
    result
  end
.,.,

# reduce 17 omitted

# reduce 18 omitted

module_eval(<<'.,.,', 'parser.racc', 50)
  def _reduce_19(val, _values, result)
     return [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 51)
  def _reduce_20(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 52)
  def _reduce_21(val, _values, result)
     return val[0] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 53)
  def _reduce_22(val, _values, result)
     return val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 56)
  def _reduce_23(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'parser.racc', 58)
  def _reduce_25(val, _values, result)
     return val[0].push(val[1]) 
    result
  end
.,.,

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.racc', 65)
  def _reduce_28(val, _values, result)
     return Property.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_29(val, _values, result)
     return Assign.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_30(val, _values, result)
     return [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 72)
  def _reduce_31(val, _values, result)
     return val[0].push(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 73)
  def _reduce_32(val, _values, result)
     return val[0].push(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 76)
  def _reduce_33(val, _values, result)
     return Literal.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 77)
  def _reduce_34(val, _values, result)
     return Literal.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 78)
  def _reduce_35(val, _values, result)
     return Literal.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 79)
  def _reduce_36(val, _values, result)
     return Literal.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 80)
  def _reduce_37(val, _values, result)
     return Literal.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_38(val, _values, result)
     return Literal.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 82)
  def _reduce_39(val, _values, result)
     return Variable.new(val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module SSS


